"""add tx_type to transactions

Revision ID: 8bdb359b0547
Revises: ac348c529b06
Create Date: 2025-09-10 08:59:37.636838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bdb359b0547'
down_revision: Union[str, Sequence[str], None] = 'ac348c529b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('tx_type', sa.Enum('normal', 'reembolso_credito', 'reembolso_debito', name='txtype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'tx_type')
    # ### end Alembic commands ###
